# Generated by Django 5.0.1 on 2024-01-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='sport',
        ),
    ]
