# Generated by Django 5.0.1 on 2024-01-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_experience_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.experience'),
        ),
    ]
