# Generated by Django 5.0.1 on 2024-01-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='certificationdifficulty',
            options={'verbose_name': 'Certification difficulty', 'verbose_name_plural': 'Certification difficulty'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Expirience', 'verbose_name_plural': 'Expirience'},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AlterModelOptions(
            name='usersportcertification',
            options={'verbose_name': 'User Sport Certification', 'verbose_name_plural': 'User Sport Certification'},
        ),
    ]
