# Generated by Django 5.0.1 on 2024-01-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='poststags',
            options={'verbose_name': 'Posts Tags', 'verbose_name_plural': 'Posts Tags'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagssports',
            options={'verbose_name': 'Tags Sports', 'verbose_name_plural': 'Tags Sports'},
        ),
    ]
