# Generated by Django 5.0.1 on 2024-01-26 12:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comments_options_alter_likes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models.DO_NOTHING, to='core.experience'),
        ),
    ]
