# Generated by Django 5.0.1 on 2024-01-26 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certification_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='Certifications',
        ),
        migrations.AddField(
            model_name='certificationdifficulty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificationdifficulty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
