# Generated by Django 5.0.1 on 2024-01-26 20:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_certification_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersportcertification',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=core.models.DO_NOTHING, to='core.certifications'),
        ),
    ]
