# Generated by Django 5.0.1 on 2024-01-26 20:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usersportcertification_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models.DO_NOTHING, to='core.comments'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models.DO_NOTHING, to='core.likes'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models.DO_NOTHING, to='core.posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usersportcertification',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models.DO_NOTHING, to='core.certifications'),
        ),
    ]
